namespace Stupid
{
    namespace ImageEffects
    {
        public class BuiltInPalettes
        {
            public Palette[] palettes = 
                {
                new Palette("Nostalgia Gameboy",
                    new string[] {  "#d0d058",
                                    "#a0a840",
                                    "#708028",
                                    "#405010"   }),

                new Palette("Links Awakening Gameboy",
                    new string[] {  "#5a3921",
                                    "#6b8c42",
                                    "#7bc67b",
                                    "#ffffb5"   }),

                new Palette("Kirokaze Gameboy",
                    new string[] {  "#332c50",
                                    "#46878f",
                                    "#94e344",
                                    "#e2f3e4"   }),

                new Palette("Ice Cream Gameboy",
                    new string[] {  "#7c3f58",
                                    "#eb6b6f",
                                    "#f9a875",
                                    "#fff6d3"   }),

                new Palette("2-Bit Gameboy",
                    new string[] {  "#000000",
                                    "#676767",
                                    "#b6b6b6",
                                    "#ffffff"   }),

                new Palette("Mist Gameboy",
                    new string[] {  "#2d1b00",
                                    "#1e606e",
                                    "#5ab9a8",
                                    "#c4f0c2"   }),

                new Palette("Ayy4 Gameboy",
                    new string[] {  "#00303b",
                                    "#ff7777",
                                    "#ffce96",
                                    "#f1f2da"   }),

                new Palette("Space Haze Gameboy",
                    new string[] {  "#f8e3c4",
                                    "#cc3495",
                                    "#6b1fb1",
                                    "#0b0630"   }),

                new Palette("Wish Gameboy",
                    new string[] {  "#622e4c",
                                    "#7550e8",
                                    "#608fcf",
                                    "#8be5ff"   }),

                new Palette("Virtual Boy",
                    new string[] {  "#ff0000",
                                    "#aa0000",
                                    "#550000",
                                    "#000000"   }),

                new Palette("Nintendo Entertainment System",
                    new string[] {  "#fcfcfc",
                                    "#f8f8f8",
                                    "#bcbcbc",
                                    "#7c7c7c",
                                    "#a4e4fc",
                                    "#3cbcfc",
                                    "#0078f8",
                                    "#0000fc",
                                    "#b8b8f8",
                                    "#6888fc",
                                    "#0058f8",
                                    "#0000bc",
                                    "#d8b8f8",
                                    "#9878f8",
                                    "#6844fc",
                                    "#4428bc",
                                    "#f8b8f8",
                                    "#f878f8",
                                    "#d800cc",
                                    "#940084",
                                    "#f8a4c0",
                                    "#f85898",
                                    "#e40058",
                                    "#a80020",
                                    "#f0d0b0",
                                    "#f87858",
                                    "#f83800",
                                    "#a81000",
                                    "#fce0a8",
                                    "#fca044",
                                    "#e45c10",
                                    "#881400",
                                    "#f8d878",
                                    "#f8b800",
                                    "#ac7c00",
                                    "#503000",
                                    "#d8f878",
                                    "#b8f818",
                                    "#00b800",
                                    "#007800",
                                    "#b8f8b8",
                                    "#58d854",
                                    "#00a800",
                                    "#006800",
                                    "#b8f8d8",
                                    "#58f898",
                                    "#00a844",
                                    "#005800",
                                    "#00fcfc",
                                    "#00e8d8",
                                    "#008888",
                                    "#004058",
                                    "#f8d8f8",
                                    "#787878"}),

                new Palette("Pico 8",
                    new string[] {  "#000000",
                                    "#1D2B53",
                                    "#7E2553",
                                    "#008751",
                                    "#AB5236",
                                    "#5F574F",
                                    "#C2C3C7",
                                    "#FFF1E8",
                                    "#FF004D",
                                    "#FFA300",
                                    "#FFEC27",
                                    "#00E436",
                                    "#29ADFF",
                                    "#83769C",
                                    "#FF77A8",
                                    "#FFCCAA"  }),

                new Palette("Pollen 8",
                    new string[] {  "#73464c",
                                    "#ab5675",
                                    "#ee6a7c",
                                    "#ffa7a5",
                                    "#ffe07e",
                                    "#ffe7d6",
                                    "#72dcbb",
                                    "#34acba"   }),

                new Palette("Endesga 32",
                    new string[] {  "#be4a2f",
                                    "#d77643",
                                    "#ead4aa",
                                    "#e4a672",
                                    "#b86f50",
                                    "#733e39",
                                    "#3e2731",
                                    "#a22633",
                                    "#e43b44",
                                    "#f77622",
                                    "#feae34",
                                    "#fee761",
                                    "#63c74d",
                                    "#3e8948",
                                    "#265c42",
                                    "#193c3e",
                                    "#124e89",
                                    "#0099db",
                                    "#2ce8f5",
                                    "#ffffff",
                                    "#c0cbdc",
                                    "#8b9bb4",
                                    "#5a6988",
                                    "#3a4466",
                                    "#262b44",
                                    "#181425",
                                    "#ff0044",
                                    "#68386c",
                                    "#b55088",
                                    "#f6757a",
                                    "#e8b796",
                                    "#c28569"   }),

                new Palette("Aap 64",
                    new string[] {  "#060608",
                                    "#141013",
                                    "#3b1725",
                                    "#73172d",
                                    "#b4202a",
                                    "#df3e23",
                                    "#fa6a0a",
                                    "#f9a31b",
                                    "#ffd541",
                                    "#fffc40",
                                    "#d6f264",
                                    "#9cdb43",
                                    "#59c135",
                                    "#14a02e",
                                    "#1a7a3e",
                                    "#24523b",
                                    "#122020",
                                    "#143464",
                                    "#285cc4",
                                    "#249fde",
                                    "#20d6c7",
                                    "#a6fcdb",
                                    "#ffffff",
                                    "#fef3c0",
                                    "#fad6b8",
                                    "#f5a097",
                                    "#e86a73",
                                    "#bc4a9b",
                                    "#793a80",
                                    "#403353",
                                    "#242234",
                                    "#221c1a",
                                    "#322b28",
                                    "#71413b",
                                    "#bb7547",
                                    "#dba463",
                                    "#f4d29c",
                                    "#dae0ea",
                                    "#b3b9d1",
                                    "#8b93af",
                                    "#6d758d",
                                    "#4a5462",
                                    "#333941",
                                    "#422433",
                                    "#5b3138",
                                    "#8e5252",
                                    "#ba756a",
                                    "#e9b5a3",
                                    "#e3e6ff",
                                    "#b9bffb",
                                    "#849be4",
                                    "#588dbe",
                                    "#477d85",
                                    "#23674e",

                                    "#328464",
                                    "#5daf8d",
                                    "#92dcba",
                                    "#cdf7e2",
                                    "#e4d2aa",
                                    "#c7b08b",
                                    "#a08662",
                                    "#796755",
                                    "#5a4e44",
                                    "#423934"   }),

                new Palette("Zughy 32",
                    new string[] {  "#472d3c",
                                    "#5e3643",
                                    "#7a444a",
                                    "#a05b53",
                                    "#bf7958",
                                    "#eea160",
                                    "#f4cca1",
                                    "#b6d53c",
                                    "#71aa34",
                                    "#397b44",
                                    "#3c5956",
                                    "#302c2e",
                                    "#5a5353",
                                    "#7d7071",
                                    "#a0938e",
                                    "#cfc6b8",
                                    "#dff6f5",
                                    "#8aebf1",
                                    "#8aebf1",
                                    "#3978a8",
                                    "#394778",
                                    "#39314b",
                                    "#564064",
                                    "#8e478c",
                                    "#cd6093",
                                    "#ffaeb6",
                                    "#f4b41b",
                                    "#f47e1b",
                                    "#e6482e",
                                    "#a93b3b",
                                    "#827094",
                                    "#4f546b"   }),

                new Palette("Pear 36",
                    new string[] {  "#5e315b",
                                    "#8c3f5d",
                                    "#ba6156",
                                    "#f2a65e",
                                    "#ffe478",
                                    "#cfff70",
                                    "#8fde5d",
                                    "#3ca370",
                                    "#3d6e70",
                                    "#323e4f",
                                    "#322947",
                                    "#473b78",
                                    "#4b5bab",
                                    "#4da6ff",
                                    "#66ffe3",
                                    "#ffffeb",
                                    "#c2c2d1",
                                    "#7e7e8f",
                                    "#606070",
                                    "#43434f",
                                    "#272736",
                                    "#3e2347",
                                    "#57294b",
                                    "#964253",
                                    "#e36956",
                                    "#ffb570",
                                    "#ffb570",
                                    "#eb564b",
                                    "#b0305c",
                                    "#73275c",
                                    "#422445",
                                    "#5a265e",
                                    "#80366b",
                                    "#bd4882",
                                    "#ff6b97",
                                    "#ffb5b5"   }),

                new Palette("Journey",
                    new string[] {  "#050914",
                                    "#110524",
                                    "#3b063a",
                                    "#691749",
                                    "#9c3247",
                                    "#d46453",
                                    "#f5a15d",
                                    "#ffcf8e",
                                    "#ff7a7d",
                                    "#ff417d",
                                    "#d61a88",
                                    "#94007a",
                                    "#42004e",
                                    "#220029",
                                    "#100726",
                                    "#25082c",
                                    "#3d1132",
                                    "#73263d",
                                    "#bd4035",
                                    "#ed7b39",
                                    "#ffb84a",
                                    "#fff540",
                                    "#c6d831",
                                    "#77b02a",
                                    "#429058",
                                    "#2c645e",
                                    "#153c4a",
                                    "#052137",
                                    "#0e0421",
                                    "#0c0b42",
                                    "#032769",
                                    "#144491",
                                    "#488bd4",
                                    "#78d7ff",
                                    "#b0fff1",
                                    "#faffff",
                                    "#c7d4e1",
                                    "#928fb8",
                                    "#5b537d",
                                    "#392946",
                                    "#24142c",
                                    "#0e0f2c",
                                    "#132243",
                                    "#1a466b",
                                    "#10908e",
                                    "#28c074",
                                    "#3dff6e",
                                    "#f8ffb8",
                                    "#f0c297",
                                    "#cf968c",
                                    "#8f5765",
                                    "#52294b",
                                    "#0f022e",
                                    "#35003b",
                                    "#64004c",
                                    "#9b0e3e",
                                    "#d41e3c",
                                    "#ed4c40",
                                    "#ff9757",
                                    "#d4662f",
                                    "#9c341a",
                                    "#691b22",
                                    "#450c28",
                                    "#2d002e"   }),

                new Palette("Journey",
                    new string[] {  "#ff0040",
                                    "#131313",
                                    "#1b1b1b",
                                    "#272727",
                                    "#3d3d3d",
                                    "#5d5d5d",
                                    "#858585",
                                    "#b4b4b4",
                                    "#ffffff",
                                    "#c7cfdd",
                                    "#92a1b9",
                                    "#657392",
                                    "#424c6e",
                                    "#2a2f4e",
                                    "#1a1932",
                                    "#0e071b",
                                    "#1c121c",
                                    "#391f21",
                                    "#5d2c28",
                                    "#8a4836",
                                    "#bf6f4a",
                                    "#e69c69",
                                    "#f6ca9f",
                                    "#f9e6cf",
                                    "#edab50",
                                    "#e07438",
                                    "#c64524",
                                    "#8e251d",
                                    "#ff5000",
                                    "#ed7614",
                                    "#ffa214",
                                    "#ffc825",
                                    "#ffeb57",
                                    "#d3fc7e",
                                    "#99e65f",
                                    "#5ac54f",
                                    "#33984b",
                                    "#1e6f50",
                                    "#134c4c",
                                    "#0c2e44",
                                    "#00396d",
                                    "#0069aa",
                                    "#0098dc",
                                    "#00cdf9",
                                    "#0cf1ff",
                                    "#94fdff",
                                    "#fdd2ed",
                                    "#f389f5",
                                    "#db3ffd",
                                    "#7a09fa",
                                    "#3003d9",
                                    "#0c0293",
                                    "#03193f",
                                    "#3b1443",
                                    "#622461",
                                    "#93388f",
                                    "#ca52c9",
                                    "#c85086",
                                    "#f68187",
                                    "#f5555d",
                                    "#ea323c",
                                    "#c42430",
                                    "#891e2b",
                                    "#571c27"   }),

                new Palette("Vinik 24",
                    new string[] {  "#000000",
                                    "#6f6776",
                                    "#9a9a97",
                                    "#c5ccb8",
                                    "#8b5580",
                                    "#c38890",
                                    "#a593a5",
                                    "#666092",
                                    "#9a4f50",
                                    "#c28d75",
                                    "#7ca1c0",
                                    "#416aa3",
                                    "#8d6268",
                                    "#be955c",
                                    "#68aca9",
                                    "#387080",
                                    "#6e6962",
                                    "#93a167",
                                    "#6eaa78",
                                    "#557064",
                                    "#9d9f7f",
                                    "#7e9e99",
                                    "#5d6872",
                                    "#433455"   }),

                new Palette("Sweetie 16",
                    new string[] {  "#1a1c2c",
                                    "#5d275d",
                                    "#b13e53",
                                    "#b13e53",
                                    "#ffcd75",
                                    "#a7f070",
                                    "#38b764",
                                    "#257179",
                                    "#29366f",
                                    "#3b5dc9",
                                    "#41a6f6",
                                    "#73eff7",
                                    "#f4f4f4",
                                    "#94b0c2",
                                    "#566c86",
                                    "#333c57"  }),

                new Palette("Fantasy 24",
                    new string[] {  "#1f240a",
                                    "#39571c",
                                    "#a58c27",
                                    "#efac28",
                                    "#efd8a1",
                                    "#ab5c1c",
                                    "#183f39",
                                    "#ef692f",
                                    "#efb775",
                                    "#a56243",
                                    "#773421",
                                    "#724113",
                                    "#2a1d0d",
                                    "#392a1c",
                                    "#684c3c",
                                    "#927e6a",

                                    "#276468",
                                    "#ef3a0c",
                                    "#45230d",
                                    "#3c9f9c",
                                    "#9b1a0a",
                                    "#36170c",
                                    "#550f0a",
                                    "#300f0a"   }),

                new Palette("Slso 8",
                    new string[] {  "#0d2b45",
                                    "#203c56",
                                    "#544e68",
                                    "#8d697a",
                                    "#d08159",
                                    "#ffaa5e",
                                    "#ffd4a3",
                                    "#ffecd6"   }),

                new Palette("Mystic",
                    new string[] {  "#FFE3BB",
                                    "#FFDBBB",
                                    "#FFD6BD",
                                    "#FFD5C4",
                                    "#FECDBF",
                                    "#FFC8C3",
                                    "#FFC3C2",
                                    "#FFBFC3",
                                    "#FFBAC4",
                                    "#FFB7C5",
                                    "#FFB7C5",
                                    "#F3AEC3",
                                    "#F3A6C6",
                                    "#F7A1C8",
                                    "#EF97C7",
                                    "#DD8CC6",
                                    "#D488C6",
                                    "#CB85C3",
                                    "#A776BB",
                                    "#976FB6",
                                    "#8569B4",
                                    "#7762B1",
                                    "#715BA4"  }),

                    new Palette("Night Club",
                    new string[] {  "#000000",
                                    "#041020",
                                    "#061428",
                                    "#0A264D",
                                    "#0C3064",
                                    "#0E3A77",
                                    "#134FA3",
                                    "#134997",
                                    "#1C74EE",
                                    "#2BAFFF",
                                    "#38C5F8",
                                    "#12DCFE",
                                    "#31FFFF",
                                    "#F7FEFE"   }),

                new Palette("Sunset",
                    new string[] {  "#000000",
                                    "#350769",
                                    "#3B0769",
                                    "#480769",
                                    "#540769",
                                    "#5F0769",
                                    "#6B115F",
                                    "#99197D",
                                    "#C43F86",
                                    "#DE458F",
                                    "#ED6056",
                                    "#E87503",
                                    "#E69005",
                                    "#E6A307",
                                    "#E6BD09",
                                    "#E6D709",
                                    "#E6D709",
                                    "#F2E67B",
                                    "#F7F0BC",
                                    "#FFFFFF"  }),

                new Palette("Middle Of Nowhere",
                    new string[] {  "#FF1744",
                                    "#F51743",
                                    "#EB1741",
                                    "#EB1741",
                                    "#D7173D",
                                    "#CD173F",
                                    "#C3173F",
                                    "#B91740",
                                    "#AF1740",
                                    "#A5173F",
                                    "#9B173F",
                                    "#91173F",
                                    "#87173E",
                                    "#7D173E",
                                    "#73173D",
                                    "#69173D",
                                    "#5F173D",
                                    "#55173D",
                                    "#4B173D",
                                    "#41173D",
                                    "#37173D",
                                    "#2D173D",
                                    "#23173D",
                                    "#19173D",
                                    "#0F173D",
                                    "#05173D"   }),

                new Palette("Amethyst",
                    new string[] {  "#1B112C",
                                    "#2A143D",
                                    "#47195D",
                                    "#731F7A",
                                    "#9E2083",
                                    "#B63F83",
                                    "#C8658C",
                                    "#DD8D9F",
                                    "#6EBDEA",
                                    "#6B9BCF",
                                    "#667DB4",
                                    "#5B5F90",
                                    "#544C70",
                                    "#4F415A",
                                    "#332A36"   }),

                new Palette("Crafty",
                    new string[] {  "#3A224F",
                                    "#4E2557",
                                    "#73326A",
                                    "#A34474",
                                    "#C7506B",
                                    "#E3755F",
                                    "#ED9E70",
                                    "#FCC88D",
                                    "#FFD7A3",
                                    "#FFEFC9",
                                    "#F0EBA8",
                                    "#CFF291",
                                    "#A0DE85",
                                    "#69C976",
                                    "#50AB76",
                                    "#36777A",
                                    "#2E5C6B",
                                    "#223D54",
                                    "#1F2E52" }),

                new Palette("Matt",
                    new string[] {  "#99C2DB",
                                    "#5D8BB3",
                                    "#4D6A94",
                                    "#4C5D7A",
                                    "#357985",
                                    "#4C8F82",
                                    "#78B392",
                                    "#B5E0BA",
                                    "#DFEDED",
                                    "#C6DBDE",
                                    "#A7B8C2",
                                    "#728794",
                                    "#4E4D5C",
                                    "#5C4D4D",
                                    "#997D76",
                                    "#C7B198",
                                    "#DFD3C3",
                                    "#F0ECE2",
                                    "#E6A3A3",
                                    "#995C95",
                                    "#5A526B",
                                    "#3D3957",
                                    "#391154",
                                    "#5B106E",
                                    "#911D55",
                                    "#BF2651",
                                    "#F54F4F",
                                    "#FF8766",
                                    "#FFAC7F",
                                    "#FFD3A3",
                                    "#FAFAC3",
                                    "#E6CF8A",
                                    "#D6A57A",
                                    "#B3785D",
                                    "#9C4F41"   })
            };
        }
    }
}